apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: talent-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talent-web
  template:
    metadata:
      labels:
        app: talent-web
    spec:
      containers:
        - name: web
          image: pf-talent-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3010
          env:
            - name: PORT
              value: "3010"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: TALENT_API_URL
              value: http://api.p10.svc.cluster.local:8090
            - name: CALENDAR_PUBLIC_WEB_URL
              value: http://calendar.localhost
            - name: OIDC_ISSUER
              value: http://idp.localhost
            - name: OIDC_INTERNAL_BASE
              value: http://idp.p01.svc.cluster.local:8080
            - name: OIDC_CLIENT_ID
              value: pf-talent-web
            - name: OIDC_REDIRECT_URI
              value: http://talent.localhost/callback
            - name: OIDC_POST_LOGOUT_REDIRECT_URI
              value: http://talent.localhost/logged-out
          readinessProbe:
            httpGet:
              path: /ready
              port: 3010
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3010
            initialDelaySeconds: 20
            periodSeconds: 10
