apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p10

resources:
  - deployment-web.yaml
  - service-web.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: portfolio-integration
    includeSelectors: false
